### ISSUE TITLE
Teach mypy more about uqbar.graphs.Attachable

### ISSUE THREAD

**Issue by trevorbaca** [josiah-wolf-oberholtzer/uqbar#34]
mypy 0.720 breaks in two places each in `RecordField` and `TableCell`:

/Users/trevorbaca/tmp/typehints/uqbar/graphs/RecordField.py:7: error: Module "uqbar.graphs.Attachable" is not valid as a type
/Users/trevorbaca/tmp/typehints/uqbar/graphs/RecordField.py:7: error: Invalid base class "Attachable"
/Users/trevorbaca/tmp/typehints/uqbar/graphs/TableCell.py:7: error: Module "uqbar.graphs.Attachable" is not valid as a type
/Users/trevorbaca/tmp/typehints/uqbar/graphs/TableCell.py:7: error: Invalid base class "Attachable"

All four breaks look like the same thing, having to do with the typing status of `Attachable`.

**Comment by josiah-wolf-oberholtzer** [comment]
Done in https://github.com/josiah-wolf-oberholtzer/uqbar/pull/35
