### ISSUE TITLE
Drop support for Python 3.7 at end-of-life

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [josiah-wolf-oberholtzer/uqbar#61]

**Comment by jgarte** [comment]
Hi, what are the Python versions that you plan to support for uqbar at any given release?

**Comment by josiah-wolf-oberholtzer** [comment]
Officially released (eg non-alpha) Python versions that have not reached end-of-life.

**Comment by josiah-wolf-oberholtzer** [comment]
Done.
