### ISSUE TITLE
Feature Request: Tutorial for using uqbar in a project

### ISSUE THREAD

**Issue by jgarte** [josiah-wolf-oberholtzer/uqbar#66]
Hi,

What do you think of having a tutorial showing how to use uqbar in a generic Python project to generate inheritance diagrams, API references, etc. to PDF book or website?

**Comment by josiah-wolf-oberholtzer** [comment]
Sounds great, although I don't personally have time for that for the foreseeable future.

**Comment by jgarte** [comment]
@josiah-wolf-oberholtzer Do you happen to know of any other Python projects that are using or have used uqbar besides abjad?

**Comment by josiah-wolf-oberholtzer** [comment]
Just https://github.com/josiah-wolf-oberholtzer/supriya
