### ISSUE TITLE
Do these tests fail for you?

### ISSUE THREAD

**Issue by jgarte** [josiah-wolf-oberholtzer/uqbar#67]
Hi, do these tests fail for you also?

```sh
=========================== short test summary info ============================
FAILED tests/test_sphinx_api.py::test_sphinx_api_1 - assert ('API\n'\n '***\n...
FAILED tests/test_sphinx_book.py::test_sphinx_book_text_cached - assert ('Fak...
FAILED tests/test_sphinx_book.py::test_sphinx_book_text_uncached - assert ('F...
======================== 3 failed, 101 passed in 6.84s =========================
```

**Comment by jgarte** [comment]
```sh
=========================== short test summary info ============================
FAILED tests/test_sphinx_api.py::test_sphinx_api_1 - assert ('API\n'\n '***\n...
FAILED tests/test_sphinx_book.py::test_sphinx_book_text_cached - assert ('Fak...
FAILED tests/test_sphinx_book.py::test_sphinx_book_text_uncached - assert ('F...
======================== 3 failed, 101 passed in 6.84s =========================
```

**Comment by josiah-wolf-oberholtzer** [comment]
What version of Sphinx are you on?

**Comment by jgarte** [comment]
> What version of Sphinx are you on?

5.1.1

**Comment by josiah-wolf-oberholtzer** [comment]
You didn't need to close the issue.

FWIW, I'm seeing failures under Sphinx 5.3.0 in GitHub Actions. Will look into fixing next week.

**Comment by josiah-wolf-oberholtzer** [comment]
Requirements installed in the v0.6.4 passing GHA (https://github.com/josiah-wolf-oberholtzer/uqbar/actions/runs/3309433792/jobs/5462614991):

```
Jinja2-3.1.2
MarkupSafe-2.1.1
Pygments-2.13.0
Sphinx-5.3.0
Unidecode-1.3.6
alabaster-0.7.12
attrs-22.1.0
babel-2.10.3
black-22.10.0
certifi-2022.9.24
charset-normalizer-2.1.1
click-8.1.3
coverage-6.5.0
docutils-0.19
flake8-5.0.4
idna-3.4
imagesize-1.4.1
iniconfig-1.1.1
isort-5.10.1
mccabe-0.7.0
mypy-0.982
mypy-extensions-0.4.3
packaging-21.3
pathspec-0.10.1
platformdirs-2.5.2
pluggy-1.0.0
py-1.11.0
pycodestyle-2.9.1
pyflakes-2.5.0
pyparsing-3.0.9
pytest-7.1.3
pytest-cov-4.0.0
pytz-2022.5
requests-2.28.1
snowballstemmer-2.2.0
sphinxcontrib-applehelp-1.0.2
sphinxcontrib-devhelp-1.0.2
sphinxcontrib-htmlhelp-2.0.0
sphinxcontrib-jsmath-1.0.1
sphinxcontrib-qthelp-1.0.3
sphinxcontrib-serializinghtml-1.1.5
tomli-2.0.1
types-PyYAML-6.0.12
types-docutils-0.19.1.1
typing-extensions-4.4.0
uqbar-0.6.4
urllib3-1.26.12
```

Requirements installed in the failing GHA (https://github.com/josiah-wolf-oberholtzer/uqbar/actions/runs/3642179788/jobs/6148988835):

```
Jinja2-3.1.2
MarkupSafe-2.1.1
Pygments-2.13.0
Sphinx-5.3.0
Unidecode-1.3.6
alabaster-0.7.12
attrs-22.1.0
babel-2.11.0
black-22.10.0
certifi-2022.9.24
charset-normalizer-2.1.1
click-8.1.3
coverage-6.5.0
docutils-0.19
exceptiongroup-1.0.4
flake8-3.9.2
idna-3.4
imagesize-1.4.1
importlib-metadata-5.1.0
iniconfig-1.1.1
isort-5.10.1
mccabe-0.6.1
mypy-0.991
mypy-extensions-0.4.3
packaging-21.3
pathspec-0.10.2
platformdirs-2.6.0
pluggy-1.0.0
pycodestyle-2.7.0
pyflakes-2.3.1
pyparsing-3.0.9
pytest-7.2.0
pytest-cov-4.0.0
pytz-2022.6
requests-2.28.1
snowballstemmer-2.2.0
sphinxcontrib-applehelp-1.0.2
sphinxcontrib-devhelp-1.0.2
sphinxcontrib-htmlhelp-2.0.0
sphinxcontrib-jsmath-1.0.1
sphinxcontrib-qthelp-1.0.3
sphinxcontrib-serializinghtml-1.1.5
tomli-2.0.1
typed-ast-1.5.4
types-PyYAML-6.0.12.2
types-docutils-0.19.1.1
typing-extensions-4.4.0
uqbar-0.6.4
urllib3-1.26.13
zipp-3.11.0
```

And the diff of the two requirements:

```
--- a/v0.6.4.txt
+++ b/v0.6.5.txt
@@ -5,32 +5,33 @@ Sphinx-5.3.0
 Unidecode-1.3.6
 alabaster-0.7.12
 attrs-22.1.0
-babel-2.10.3
+babel-2.11.0
 black-22.10.0
 certifi-2022.9.24
 charset-normalizer-2.1.1
 click-8.1.3
 coverage-6.5.0
 docutils-0.19
-flake8-5.0.4
+exceptiongroup-1.0.4
+flake8-3.9.2
 idna-3.4
 imagesize-1.4.1
+importlib-metadata-5.1.0
 iniconfig-1.1.1
 isort-5.10.1
-mccabe-0.7.0
-mypy-0.982
+mccabe-0.6.1
+mypy-0.991
 mypy-extensions-0.4.3
 packaging-21.3
-pathspec-0.10.1
-platformdirs-2.5.2
+pathspec-0.10.2
+platformdirs-2.6.0
 pluggy-1.0.0
-py-1.11.0
-pycodestyle-2.9.1
-pyflakes-2.5.0
+pycodestyle-2.7.0
+pyflakes-2.3.1
 pyparsing-3.0.9
-pytest-7.1.3
+pytest-7.2.0
 pytest-cov-4.0.0
-pytz-2022.5
+pytz-2022.6
 requests-2.28.1
 snowballstemmer-2.2.0
 sphinxcontrib-applehelp-1.0.2
@@ -40,8 +41,10 @@ sphinxcontrib-jsmath-1.0.1
 sphinxcontrib-qthelp-1.0.3
 sphinxcontrib-serializinghtml-1.1.5
 tomli-2.0.1
-types-PyYAML-6.0.12
+typed-ast-1.5.4
+types-PyYAML-6.0.12.2
 types-docutils-0.19.1.1
 typing-extensions-4.4.0
 uqbar-0.6.4
-urllib3-1.26.12
+urllib3-1.26.13
+zipp-3.11.0
```

**Comment by jgarte** [comment]
The reason it failed is because I was using sphinx installed via Guix which is at `5.1.1` versus PyPi:

https://packages.guix.gnu.org/packages/python-sphinx/5.1.1/

I have to update the sphinx package in Guix 😄

**Comment by josiah-wolf-oberholtzer** [comment]
We might be talking past each other.

The tests are failing without any Python code or requirements changes between October and now. See my comment just before yours. Uqbar with Sphinx 5.3.0 worked in October and now it doesn't, probably due to transitive dependencies being updated.

**Comment by jgarte** [comment]
Got it. Thanks for clarifying.

I'll wait for you to do more testing on your end.

Keep me posted.

I have a Guix package for uqbar here:

https://packages.guix.gnu.org/packages/python-uqbar/0.5.6/

**Comment by josiah-wolf-oberholtzer** [comment]
Have to admit I still don't understand the appeal of repackaging Python packages for (insert Linux distro / package manager here).

**Comment by jgarte** [comment]
I think it is just yet another tool that people are using to provide reproducibility of your environment for a Python development project.

Guix System is the other killer feature that lets you automate services in Scheme and deploy them in tandem

**Comment by jgarte** [comment]
> Have to admit I still don't understand the appeal of repackaging Python packages for (insert Linux distro / package manager here).

I agree that what Guix should provide is powerful tools to generate Guix packages for a given project based on what you need instead of trying to package PyPi and the world.

I think Nix might be doing a better job of this currently:

https://github.com/nix-community/poetry2nix

Speaking of PyPi:

https://github.com/on-nix/python

BTW, Guix is a fork of Nix. Guix even uses the nix daemon still from the time it forked Nix more or less.

**Comment by josiah-wolf-oberholtzer** [comment]
Honestly, if I never looked at Scheme again, that would be fine with me 😂.

I'm not a poetry user either. Virtualenv and pip work fine for me for local development, and anything deployed uses Docker (again with regular pip for Python applications).

**Comment by jgarte** [comment]
I use pip and docker also.

> Honestly, if I never looked at Scheme again, that would be fine with me joy.

It's a love hate relationship for me with Scheme. It's complicated.

**Comment by jgarte** [comment]
Awesome! THNX!!
