### ISSUE TITLE
Feature Request: GitHub Pages Documentation Deploy with Latest Documentation Via CI

### ISSUE THREAD

**Issue by jgarte** [josiah-wolf-oberholtzer/uqbar#70]
Hi,

What do you think of CI building the latest GitHub Pages Documentation Release like there is here:

https://uqbar.readthedocs.io/en/latest/api/

I'd make a PR but I think this requires enabling fiddling with settings in the admin panel for your account iirc

**Comment by josiah-wolf-oberholtzer** [comment]
Docs are already built and pushed to gh-pages on every release. I think that's good enough for me.

**Comment by josiah-wolf-oberholtzer** [comment]
Reminds me that I need to delete the ancient readthedocs version.

**Comment by josiah-wolf-oberholtzer** [comment]
Readthedocs has been retired ☠️

**Comment by jgarte** [comment]
That's awesome! But what happened to all of the fancy graphviz class diagrams in the docs similar to https://abjad.github.io/api/abjad/pcollections.html#module-abjad.pcollections?

**Comment by josiah-wolf-oberholtzer** [comment]
The inheritance diagrams don't show up because I've suppressed them for Uqbar's docs.

It's possible to distribute the PDF, but I've chosen not to because the layout is significantly worse than the HTML version.

**Comment by josiah-wolf-oberholtzer** [comment]
You're welcome to check out the code and build the PDF version yourself.

**Comment by jgarte** [comment]
> You're welcome to check out the code and build the PDF version yourself.

Would that be a `make -C docs/ pdf` in the root of the repo?

**Comment by jgarte** [comment]
Should a rule be added to the `Makefile` in order to generate the PDF version?

**Comment by jgarte** [comment]
If so, I can open a PR for that ;()

**Comment by jgarte** [comment]
Or, this is just implicit functionality of a sphinx Makefile so advanced users should just read the sphinx docs to know how to generate the pdf?

**Comment by jgarte** [comment]
Got it, thanx!

**Comment by josiah-wolf-oberholtzer** [comment]
And to be explicit:
- The Makefile is for developer tasks I personally use when working on the project
- The docs/Makefile is generated by Sphinx, and provides a variety of targets (which may work or not to varying degrees)
- I don't personally care about any of those sphinx-build targets except for `clean` and `html`
- You're welcome to try to build the docs in any of the formats that Sphinx supports, but I will not attempt to make any guarantees or put any effort into any of them besides `html`

**Comment by jgarte** [comment]
> The inheritance diagrams don't show up because I've suppressed them for Uqbar's docs.

Hi @josiah-wolf-oberholtzer 

What is the option to enable the inheritance diagrams?

**Comment by jgarte** [comment]
Thanks! I'll give that a try soon with a project.
