### ISSUE TITLE
Reimplement delimit_words

### ISSUE THREAD

**Issue by jgarte** [josiah-wolf-oberholtzer/uqbar#79]
Hi,

Why does `delimit_words` need to be re-implemented? 

You left a `TODO` comment here:

https://github.com/josiah-wolf-oberholtzer/uqbar/blob/main/uqbar/strings.py#L44

Is it because the function is too long?

**Comment by josiah-wolf-oberholtzer** [comment]
Probably. Probably could be mostly solved by a regex.

**Comment by jgarte** [comment]
What was the idea with the `wordlike_characters` checking variable?

I see in a repl that this function ignore characters like `@`, `#`, `$`, `%, `^`, `&`, `*`, etc.

```python
>>> list(delimit_words("<hello><world>!"))
['<', 'hello', '><', 'world', '>!']
```

```python
>>> list(delimit_words("!!!go go power rangers!!!"))
['!!!', 'go', 'go', 'power', 'rangers', '!!!']
```

**Comment by josiah-wolf-oberholtzer** [comment]
Looks like it's mainly used to break up class names into component words, e.g. `AbstractClass` -> `["Abstract", "class"]`

https://github.com/josiah-wolf-oberholtzer/uqbar/blob/2ec2309daca511117018bf14eb0d6b50938f50ca/uqbar/apis/graphs.py#L354

Are you looking to reimplement this, or just asking questions? If you're just poking around, take it to the discussions section you previously asked for.

**Comment by jgarte** [comment]
I would like to reimplement it, yes, for practice, but I'm first trying to scope out what would be accepted/needed for it in a PR.
